version: "3.7"
services:
  api-tests:
    tty: false
    build:
      context: .
      dockerfile: Dockerfile-tests
    volumes:
      - "./src:/src"
      - "./tests:/tests"
    expose:
      - 8000
    ports:
      - "8019:8000"
